
raw_cibil_data_path: "data/raw_data/Cibil_Data_External.xlsx"
raw_internal_data_path: "data/raw_data/Internal_data_Bank.xlsx"
train_data_path: "data/train_data/cust_train_data.csv"
val_data_path: "data/validation_data/cust_val_data.csv"
output_model_path: "src/models"
# output_transformer_path: "src/models/transformer.pkl"
# metric_path: "src/models/metrics.json"
feature_store_path: "src/models/final_features_after_feature_selection.json"
feature_encoded_classifier_path: "src/models/feature_risk_modelling_column_trans_classifier.pkl"
label_encoder_classifier_path: "src/models/label_encoding_risk_modelling_classifier.pkl"
experiment_dir: "src/experiments"
