
raw_cibil_data_path: "data/raw_data/Cibil_Data_External.xlsx"
raw_internal_data_path: "data/raw_data/Internal_data_Bank.xlsx"
input_data_path: "data/train_data/cust_train_data.csv"
output_model_path: "src/models/model_"
output_transformer_path: "src/models/transformer.pkl"
metric_path: "src/models/metrics.json"