# @package _group_
categorical_features:
  - "alchemy_category;14"
  - "website;30"
  - "website_type;30"
  - "website_type2;14"
  - "domain;14"
numerical_features:
  - "alchemy_category_score"
  - "avglinksize"
  - "commonlinkratio_1"
  - "commonlinkratio_2"
  - "commonlinkratio_3"
  - "commonlinkratio_4"
  - "compression_ratio"
  - "embed_ratio"
  - "framebased"
  - "frameTagRatio"
  - "hasDomainLink"
  - "html_ratio"
  - "image_ratio"
  - "is_news"
  - "lengthyLinkDomain"
  - "linkwordscore"
  - "news_front_page"
  - "non_markup_alphanum_characters"
  - "numberOfLinks"
  - "numwords_in_url"
  - "parametrizedLinkRatio"
  - "spelling_errors_ratio"
target_col: "label"
normalize_numerical: False

